### ISSUE TITLE
User model

### ISSUE THREAD

**Issue by ajeygore** [codeignition/hachi#1]
User model should have following attributes
1. mail - user email attribute
2. name - user name (short name, everything before @ symbol )
3. dn - this will be looked up from ldap and setup here to position it later. 
4. sshPublicKey - this will be looked up from and set to ldap
5. uid - same as name 
6. uidNumber - this will be number starting from 10001
7. userPassword - this will be the password which we sync to ldap
8. gidNumber - group id number - this will be an array

**Comment by exagil** [comment]
except mail, name, uid and userPassword, which fields should not be empty?

**Comment by ajeygore** [comment]
everything else can be empty.  

@ajeygore

ajeygore.in

**Comment by exagil** [comment]
should the uid change if there is a change in name?

**Comment by ajeygore** [comment]
No, UID once given won't change.  

@ajeygore

ajeygore.in
